const express = require("express");
const app = express();
const urlRoute = require("./routes/url");
const userRoute = require("./routes/user");
const { connectMongoDb } = require("./connection");
const PORT = 8001;
app.use(express.json());
connectMongoDb("mongodb://127.0.0.1:27017/url-shortner");
app.use("/", urlRoute);
app.use("/user", userRoute);
app.listen(PORT, () => console.log("server started at : ", PORT));
